### ISSUE TITLE
Blocking channels on main page & whole Games

### ISSUE THREAD

**Issue by therealmaxmoon** [kwaschny/unwanted-twitch#6] opened 2018-09-28 07:32 UTC
I've blocked the "Game" ASMR, but on the main page, there are still recommendations of ASMR channels. Is it possible to go to a Game page like https://www.twitch.tv/directory/game/ASMR and click a button, "block all channels in ASMR"? Because that's what I did by hand and it took a while. But this fixed the problem to get those ASMR channels on the main page. Or might it be possible to block all blacklisted games on the main page?

A "hide channel" button for channels which are shown on the main page, does not exist.

**Comment by kwaschny** [comment] 2018-09-29 00:43
This might be an issue where the game of the channel cannot be detected and thus the channel is not blocked through the game. Can you please provide the URL and a screenshot with the "recommendations" you are referring to?

**Comment by therealmaxmoon** [comment] 2018-09-29 19:46
Ok, I don't know what it was, but after reloading the page there was just a white gap left. Maybe it was a false alarm...

But the buttons don't exist, like in the game list: 
[screenshot](https://i.postimg.cc/37p1V4bb/asmr_is_blocked.png)

**Comment by therealmaxmoon** [comment] 2018-09-29 19:47
Closing the issue, because I can't reconstruct it anymore :)

**Comment by therealmaxmoon** [comment] 2018-09-29 20:05
Ok, I could reconstruct it!

1. Visit a random channel directly by clicking on a link, like [mine](https://www.twitch.tv/maxmoon2050)
2. Click on the twitch logo to go to the main page to see recommended channels. I can see a channel, which I've blocked and was a white gap before.
3. Reload the page. White gap is back

**Comment by kwaschny** [comment] 2018-10-05 00:09
The issue is most likely related to having this race condition in the currently published version: 4784b07ea0d5cdb24c538bb7f872fd0ca0ffae82

You will have to check if it's gonna be fixed with the next version.

**Comment by therealmaxmoon** [comment] 2018-11-08 08:29
With 18.10.13 I have even more issues, now. I can't get any white gaps anymore. The blocked games are on the main page at twitch all the time (recommended channels and games).

**Comment by kwaschny** [comment] 2018-11-08 12:14
Actually Twitch just changed the view in the meanwhile. I will prepare a fix.

**Comment by kwaschny** [comment] 2018-11-08 13:55
Frontpage filter (f2fcad2d2bcd42ad994c0b2902c113ce08c394c2) and "Hide Tag" button (8688a25cabf56c7bc1e34531267b4a0de1d40420) fixed with update version `18.11.8`.

**Closed by kwaschny** 2018-11-08 13:55 UTC
Labels: fixed
