### ISSUE TITLE
Custom tag case sensitivity

### ISSUE THREAD

**Issue by Fusha** [kwaschny/unwanted-twitch#93] opened 2022-08-14 19:03 UTC
Twitch has custom tags now, so it would make sense for the tag filter to be case insensitive. Right now, case sensitivity works weird: if I filter «PNGtuber» by clicking on the x next to the tag, «PNGtuber» will be hidden, but «pngtuber» will still show. But if I filter «pngtuber», both «PNGtuber» and «pngtuber» and all other case variations will be correctly hidden.

**Comment by kwaschny** [comment] 2022-08-14 19:43
All blocked terms are supposed to be case-insensitive, so that's a bug then. I'll check it.

**Comment by kwaschny** [comment] 2022-08-14 21:09
This has been addressed with 25def56a98cd64b515e8bd134319c3f0a1f57bf7. I also decided to normalize blocked terms and ignore diacritics in them. This will make it less likely to encounter _"didn't I already block this?!"_ moments, hopefully.

**Comment by Fusha** [comment] 2022-08-16 17:11
Works like a charm now, thank you for your work!

**Comment by sublimal** [comment] 2022-10-17 08:17
I believe this update broke regular expressions and/or case-sensitive matching. If I add `/^[^a-z]+$/I` what is stored is `/[a-z]+$/i`
![image](https://user-images.githubusercontent.com/4757622/196123238-973ccd57-8659-4ea0-b68c-75e834f2fc00.png)

I'm also unable to add a literal '^' to any blacklist

**Comment by kwaschny** [comment] 2022-10-18 21:00
Regression bug caused by 25def56a98cd64b515e8bd134319c3f0a1f57bf7.

**Comment by kwaschny** [comment] 2022-10-18 22:08
Fixed with 932c7ef90130af31becdd2d2b9a84d0ddb6bc1ee.

**Comment by kwaschny** [comment] 2022-11-03 22:22
Fixed in version: `22.11.3`

**Closed by kwaschny** 2022-11-03 22:22 UTC
Labels: bug, resolved
