### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gozaru000** [kwaschny/unwanted-twitch#85] opened 2022-06-16 23:43 UTC
The old black list is not valid
When adding a new blacklist, it seems that the title is also included as part of the name

**Comment by kwaschny** [comment] 2022-06-17 00:43
Duplicate of #84 ? Are you on the newest version `22.06.15` that was just released yesterday for Chrome? Firefox and Edge updates are still being reviewed.

**Comment by gozaru000** [comment] 2022-06-18 10:39
I'm using firefox
It looks like the problem has been solved 
Thank you for your maintenance

**Closed** 2022-06-18 10:43 UTC
Labels: duplicate
